2021-03-15 17:45:38,991 ERROR: Exception on /auth/confirm [GET] [in /Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/weiqidu/project/website_new/app/auth/routes.py", line 83, in resend_confirmation
    send_confirm_email(user)
  File "/Users/weiqidu/project/website_new/app/auth/email.py", line 17, in send_confirm_email
    token = user.generate_confirmation_token()
AttributeError: 'NoneType' object has no attribute 'generate_confirmation_token'
2021-03-15 17:45:55,264 INFO: Microblog startup [in /Users/weiqidu/project/website_new/app/__init__.py:92]
2021-03-15 17:46:00,359 ERROR: Exception on /auth/confirm [GET] [in /Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/weiqidu/project/website_new/app/auth/routes.py", line 83, in resend_confirmation
    send_confirm_email(user)
  File "/Users/weiqidu/project/website_new/app/auth/email.py", line 17, in send_confirm_email
    token = user.generate_confirmation_token()
AttributeError: 'NoneType' object has no attribute 'generate_confirmation_token'
2021-03-15 19:40:32,617 INFO: Microblog startup [in /Users/weiqidu/project/website_new/app/__init__.py:92]
2021-03-15 19:40:37,277 ERROR: Exception on /auth/confirm [GET] [in /Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/weiqidu/project/website_new/app/auth/routes.py", line 83, in resend_confirmation
    send_confirm_email(user)
  File "/Users/weiqidu/project/website_new/app/auth/email.py", line 17, in send_confirm_email
    token = user.generate_confirmation_token()
AttributeError: 'NoneType' object has no attribute 'generate_confirmation_token'
2021-03-15 19:40:59,668 INFO: Microblog startup [in /Users/weiqidu/project/website_new/app/__init__.py:92]
2021-03-15 19:41:06,947 ERROR: Exception on /auth/confirm [GET] [in /Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/weiqidu/project/website_new/app/auth/routes.py", line 83, in resend_confirmation
    send_confirm_email(user)
  File "/Users/weiqidu/project/website_new/app/auth/email.py", line 17, in send_confirm_email
    token = user.generate_confirmation_token()
AttributeError: 'NoneType' object has no attribute 'generate_confirmation_token'
2021-03-15 19:52:33,192 INFO: Microblog startup [in /Users/weiqidu/project/website_new/app/__init__.py:92]
2021-03-15 19:52:46,889 INFO: Microblog startup [in /Users/weiqidu/project/website_new/app/__init__.py:92]
2021-03-15 19:52:51,806 ERROR: Exception on /auth/confirm [GET] [in /Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/weiqidu/project/website_new/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/weiqidu/project/website_new/app/auth/routes.py", line 83, in resend_confirmation
    send_confirm_email(user)
  File "/Users/weiqidu/project/website_new/app/auth/email.py", line 17, in send_confirm_email
    token = user.generate_confirmation_token()
AttributeError: 'NoneType' object has no attribute 'generate_confirmation_token'
2021-03-15 19:58:37,327 INFO: Microblog startup [in /Users/weiqidu/project/website_new/app/__init__.py:92]
